SELECT 
	PROGRAM_NUMBER,
	substring(PROGRAMS_GAS.PROGRAM_NAME,1,locate(char(0),PROGRAMS_GAS.PROGRAM_NAME)-1) as PROGRAM_NAME,
	STEP_NO,
	T_G_MODE,
	T_G_FLOW,
	T_G_OXYG,
	INSERTED,
	T_G_TIME_WIDTH
FROM 
	PROGRAMS_GAS 
WHERE
	year(date(inserted))=? and PROGRAM_NUMBER=?;